feat: allow listing all invoices
Tietokilta/laskugeneraattori pull request #10
Opened 2024-02-01 18:43 UTC by Jooakar

Allows listing all populated invoices with `GET /invoices`

2024-02-01 21:48 UTC, lajp requested changes
This looks good!
Only a couple of small things.

It'd also be nice if you could write tests for the feature. It should easy to write a couple of tests based on the existing ones.

2024-02-01 21:48 UTC, lajp commented on src/api/mod.rs
> +        .route("/invoices", get(invoices::list_all))
this can be combined with the previous line:
```rust
.route("/invoices", get(invoices::list_all).post(invoices::create))
```

2024-02-01 21:48 UTC, lajp commented on src/api/invoices.rs
> +) -> Result<(StatusCode, Json<Vec<PopulatedInvoice>>), Error> {
The `StatusCode` doesn't need to be explicitly specified when its OK.

2024-02-01 21:48 UTC, lajp commented on src/database/invoices.rs
> +                .into_iter()
diesel_async supports streams that can be directly collected into a container that is not `Vec<T>`
See: https://docs.rs/diesel-async/latest/diesel_async/trait.RunQueryDsl.html#method.load_stream

2024-02-08 21:25 UTC, Jooakar reviewed
Added two new tests, not entirely sure how testing should be approached in a project like this (or in general :D) so feedback would be appreciated

2024-02-08 21:25 UTC, Jooakar commented on src/database/invoices.rs
> +                .into_iter()
changed this in d6d41c0d42463fda7fcb812b517601c9e2729766 to use the recommended method

2024-02-12 16:05 UTC, lajp approved these changes
lgtm!
Thanks for your contribution!

2024-02-12 16:23 UTC, merged